version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: artembespalov/backend_foodgram
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: artembespalov/frontend_foodgram
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  db_postgres:
  static_value:
  media_value: